on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: "yarn"
          registry-url: "https://registry.yarnpkg.com"
          corepack: true

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build Storybook
        run: yarn run build-storybook

      - name: Lost Pixel
        run: yarn run visual-regression
