on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.1.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn run build-storybook

      - name: Run Visual Regression
        run: |
          # Download Playwright(PW) Browsers for specific-version
          # Each version of Playwright needs specific versions of Chromium Webkit and Firefox so defining version is necessary

          # chromium
          PLAYWRIGHT_BROWSERS_PATH=/usr/lib/playwright yarn add playwright-chromium@1.42.1

          #  webkit
          PLAYWRIGHT_BROWSERS_PATH=/usr/lib/playwright yarn add playwright-webkit@1.42.1

          # firefox
          PLAYWRIGHT_BROWSERS_PATH=/usr/lib/playwright yarn add playwright-firefox@1.42.1

          # ask playwright to launch browsers from specific path
          PLAYWRIGHT_BROWSERS_PATH=/usr/lib/playwright yarn run visual-regression
